## Import library

In [33]:
import pandas as pd 
import sklearn

## Read data

In [34]:
data = pd.read_csv('german_credit_data.csv', index_col = 0)

In [35]:
data

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,49,male,1,own,little,NaN,2096,12,education,good
3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,53,male,2,free,little,little,4870,24,car,bad
...,...,...,...,...,...,...,...,...,...,...
995,31,female,1,own,little,NaN,1736,12,furniture/equipment,good
996,40,male,3,own,little,little,3857,30,car,good
997,38,male,2,own,little,NaN,804,12,radio/TV,good
998,23,male,2,free,little,little,1845,45,radio/TV,bad
999,27,male,2,own,moderate,moderate,4576,45,car,good

## Preprocessing

In [36]:
def preprocess_missing_value(data):
    mode_saving_accounts = data['Saving accounts'].mode()
    data['Saving accounts'].fillna(mode_saving_accounts[0], inplace=True)

    mode_checking_account = data['Checking account'].mode()
    data['Checking account'].fillna(mode_checking_account[0], inplace=True)

def preprocessing(data):
    for column in ['Saving accounts', 'Checking account']:
        data[column] = data[column].fillna('nan')
    data['Saving accounts'] = data['Saving accounts'].fillna('nan')

    data['Sex'] = data['Sex'].apply(lambda x: 1 if x == 'male' else 0)
    data['Risk'] = data['Risk'].apply(lambda x: 1 if x == 'good' else 0)
    data['Housing'] = data['Housing'].apply(lambda x: 0 if x == 'free' else (1 if x == 'own' else 2))
    data['Saving accounts'] = data['Saving accounts'].apply(lambda x: 0 if x == 'nan' 
                                                                        else(1 if x == 'little' 
                                                                        else(2 if x == 'moderate'
                                                                        else(3 if x == 'quite rich' 
                                                                        else 4))))
                                                                        
    data['Checking account'] = data['Checking account'].apply(lambda x: 0 if x == 'nan' 
                                                                        else(1 if x == 'little' 
                                                                        else(2 if x == 'moderate'
                                                                        else(3 if x == 'quite rich' 
                                                                        else 4))))
    data['Purpose'] = data['Purpose'].apply(lambda x: 5 if x == 'car' 
                                                        else (4 if x == 'radio/TV'
                                                        else (3 if x == 'furniture/equipment'
                                                        else (2 if x == 'business'
                                                        else (1 if x == 'education'
                                                        else 0)))))

In [37]:
preprocess_missing_value(data)
preprocessing(data)

In [38]:
data

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,67,1,2,1,1,1,1169,6,4,1
1,22,0,2,1,1,2,5951,48,4,0
2,49,1,1,1,1,1,2096,12,1,1
3,45,1,2,0,1,1,7882,42,3,1
4,53,1,2,0,1,1,4870,24,5,0
...,...,...,...,...,...,...,...,...,...,...
995,31,0,1,1,1,1,1736,12,3,1
996,40,1,3,1,1,1,3857,30,5,1
997,38,1,2,1,1,1,804,12,4,1
998,23,1,2,0,1,1,1845,45,4,0
999,27,1,2,1,2,2,4576,45,5,1

## Split data

In [39]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [40]:
X

,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose
0,67,1,2,1,1,1,1169,6,4
1,22,0,2,1,1,2,5951,48,4
2,49,1,1,1,1,1,2096,12,1
3,45,1,2,0,1,1,7882,42,3
4,53,1,2,0,1,1,4870,24,5
...,...,...,...,...,...,...,...,...,...
995,31,0,1,1,1,1,1736,12,3
996,40,1,3,1,1,1,3857,30,5
997,38,1,2,1,1,1,804,12,4
998,23,1,2,0,1,1,1845,45,4
999,27,1,2,1,2,2,4576,45,5

In [41]:
y

0      1
1      0
2      1
3      1
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: Risk, Length: 1000, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
X_train.shape

(800, 9)

## Decision Tree Model

In [44]:
from sklearn.tree import DecisionTreeClassifier

d_tree = DecisionTreeClassifier()
d_tree.fit(X_train, y_train)

DecisionTreeClassifier()

## Predict

In [45]:
y_predict = d_tree.predict(X_test)

## Model Evolution

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Confussion Matrix: \n", confusion_matrix(y_test, y_predict),"\n")

print("Classification report according to Test prediction: \n", classification_report(y_test, y_predict))

print ("Accuracy of KNN: %.2f %%" %(100*accuracy_score(y_test, y_predict)))

Confussion Matrix:
 [[ 22  37]
 [ 32 109]]

Classification report according to Test prediction:
               precision    recall  f1-score   support

           0       0.41      0.37      0.39        59
           1       0.75      0.77      0.76       141

    accuracy                           0.66       200
   macro avg       0.58      0.57      0.57       200
weighted avg       0.65      0.66      0.65       200

Accuracy of KNN: 65.50 %

## With Smote

In [47]:
from imblearn.over_sampling import SMOTE 

X_train_smote, y_train_smote = SMOTE(random_state = 42).fit_resample(X_train, y_train)

In [48]:
X_train_smote.shape

(1118, 9)

In [49]:
decision_tree_smote_model = DecisionTreeClassifier()
decision_tree_smote_model.fit(X_train_smote, y_train_smote)

DecisionTreeClassifier()

In [50]:
y_predict_with_smote = decision_tree_smote_model.predict(X_test)

In [51]:
print("Confussion Matrix: \n", confusion_matrix(y_test, y_predict_with_smote),"\n")

print("Classification report according to Test prediction: \n", classification_report(y_test, y_predict_with_smote))

print ("Accuracy of KNN: %.2f %%" %(100*accuracy_score(y_test, y_predict_with_smote)))

Confussion Matrix:
 [[ 26  33]
 [ 37 104]]

Classification report according to Test prediction:
               precision    recall  f1-score   support

           0       0.41      0.44      0.43        59
           1       0.76      0.74      0.75       141

    accuracy                           0.65       200
   macro avg       0.59      0.59      0.59       200
weighted avg       0.66      0.65      0.65       200

Accuracy of KNN: 65.00 %